title = "Why Not Cats"
description = ""
url = "https://blog.whynotcats.com"
keywords = "blog"
image = ""
theme = ""
lang = "en-ca"
sitemap = true
rss = true
atom = true
dates_of_creation = true
author = "Why Not Cats"
